### ISSUE TITLE
pytorch 版本

### ISSUE THREAD

**Issue by Decalogue** [tianheyu927/PCGrad#1]
您好!
请问有 pytorch 版本的吗?
多谢啦!

**Comment by tianheyu927** [comment]
Yes, we are planning to release the PyTorch version soon, probably around mid-June.

**Comment by Decalogue** [comment]
Thank you so much!

**Comment by rangwani-harsh** [comment]
As all the repositories that you have mentioned are based on Pytorch is there even a possibility of a suboptimal implementation of this currently available in pytorch?
I was trying to implement in pytorch but one of the problems is the unavailability of a vectorized_map operation which may cause performance issues?
 Thanks for the TF implementation!
