### ISSUE TITLE
it's 2022 now? Do we have a pytorch verion?

### ISSUE THREAD

**Issue by Sean-asc** [tianheyu927/PCGrad#14]

**Comment by xgxgnpu** [comment]
hello, i know a pytorch verion. [pcgrad_PytorchVersion](https://github.com/Pongpisit-Thanasutives/Multi-task-Physics-informed-neural-networks/blob/main/pcgrad.py)

**Comment by Sean-asc** [comment]
thank you for mention that!  I've used some unofficial version in my code, facing the problem of lack of GPU memerory, which the gradient parameters are two big for my network.
