### ISSUE TITLE
question about calculation of projection of gradients

### ISSUE THREAD

**Issue by woozch** [tianheyu927/PCGrad#2]
Hi. I am impressed with your work. 

While reading your paper and code, I am confused because explanations of PCGrad update rule (algorithm 1 in the paper) and code implementation (https://github.com/tianheyu927/PCGrad/blob/c5fbd7c856526373828074f06875230f7f3ee79e/PCGrad_tf.py#L44-L51) seems slightly different.

As far as I know, the "tf.vectorized_map" function runs a given "fn" function in parallel with its inputs. (https://www.tensorflow.org/api_docs/python/tf/vectorized_map)
In the code, you use tf.vectorized_map which runs a given function in parallel. The function "proj_grad" calculates inner_product value based on not updated gradients. However, in the explanation of algorithm 1 in your paper, gradients are updated sequentially.

I want to make sure that the implementation of the code and the description of the algorithm are the same.

**Comment by tianheyu927** [comment]
Hi,

The function `proj_grad` calculates the gradient projection of the current task gradient onto other **original** task gradients iteratively. This should be consistent with Algorithm 1 in the paper. Does it make sense?

**Comment by woozch** [comment]
Hi. Thanks for the reply.

What I am confused with is that the contents of "grads_task" tensor in proj_grad function do not change while tf.vectorized_map is running, but in the paper, the value of g_i changes every time through the loop iteration.
If I rewrite algorithm 1 with code as I understand it, it should be like the below.

between line 3 and 4: Set gi_new = gi
line 6: Set gi_new = gi_new - gi*gj / |gj|^2 * gj
line 9: Store gi^PC = gi_new

The difference here is that each task gradient doesn't change during the projection calculation.

**Comment by tianheyu927** [comment]
The contents of `grads_task` shouldn't change according to Algorithm 1 while `grad_task ` is updated iteratively. I think algorithm 1 is exactly doing what you wrote here except that the projection is gi_new*gj / |gj|^2 * gj. Note that the [arXiv version](https://arxiv.org/pdf/2001.06782.pdf) of the paper got updated and I guess you are looking at algorithm 1 in the previous version?

**Comment by woozch** [comment]
Ah! I think I read previous version of your paper. It is clearly stated in the updated version. Thanks a lot!

**Comment by wgchang** [comment]
I read the current version of your paper again and I'm still facing the same problem. At line 5, I think g^PC_i  should be  g_i to match with the code.
